openapi: 3.0.1

info: 
  title: API - Controle de estados
  description: Api para controle dos estados brasileiros e suas informações
  version: 0.0.1
  
  #Contatos
  contact:
    name: Yhonathan Matheus Pavan
    email: yhonathannpavan@gmail.com

#Links externos
externalDocs: 
  description: Projeto GitHub
  url: https://github.com/yhonathanpavan/Avaliacao-PB-Sprint03/

servers: 
 - url: http://localhost:8080
   description: API de teste
paths:
  /api/states:
    post:
      summary: Cria novos estados
      requestBody: 
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EstadoSemId" 
      responses:
        201:
          description: Created
          content:
           application/json:
            schema:
              $ref: "#/components/schemas/Estado"
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MensagensBadRequest"
              
    get: 
      summary: Recupera todos os estados
      parameters:
        - name: nomeRegiao
          in: query
          description: Filtra os estados por regiões (Norte, Nordeste, Sul, Sudeste e Centro_Oeste)
          schema:
            type: string
        - name: sort
          in: query
          description: Ordena a visualização dos estados por "populacao" ou "area"
          schema:
            type: string
      responses: 
        200:
          description: OK
          content: 
            application/json:
              schema:
                $ref: "#/components/schemas/Estados"
        400:
          description: Bad Request
            
  /api/states/{id}:
    parameters: 
    - name: id
      in: path 
      schema:
        type: integer
      required: true 
    get:
      summary: Recupera uma estado pelo ID
      responses:
        200:
          description: OK
          content: 
            application/json:
              schema:
                $ref: "#/components/schemas/Estado"
        404:
          description: Not Found
  
              
    put:
      summary: Altera um estado existente pelo ID
      description: "Através desse endpoint você pode atualizar novos estados brasileiros"
      requestBody: 
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EstadoSemId"
      responses:
        200:
          description: OK
          content:
           application/json:
            schema:
              $ref: "#/components/schemas/Estado"

        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MensagensBadRequest"
        404:
          description: Not Found
      

    delete:
      summary: Remove um estado pelo ID
      responses:
        200:
          description: OK

        404:
          description: Not Found
         
              
components: 
  schemas:
    Estado:
     type: object
     properties:
      id: 
        type: integer
      nome:   
        type: string
      regiao:   
        type: string
      populacao:   
        type: integer
      capital:   
        type: string
      area:   
        type: number
      
    EstadoSemId:
     type: object
     properties:
      nome:   
        type: string
      regiao:   
        type: string
      populacao:   
        type: integer
      capital:   
        type: string
      area:   
        type: number
        
    MensagensBadRequest:
      type: array
      items:
       properties:
        campo:   
          type: string
        erro:   
          type: string
          
    Estados: 
      type: array
      items:
        $ref: "#/components/schemas/Estado"

    