openapi: 3.0.1

info: 
  title: API - Controle de estados
  description: Api para controle dos estados brasileiros e suas informações
  version: 0.0.1
  
  #Contatos
  contact:
    name: Yhonathan Matheus Pavan
    email: yhonathannpavan@gmail.com

#Links externos
externalDocs: 
  description: Projeto GitHub
  url: https://github.com/yhonathanpavan/Avaliacao-PB-Sprint03/tree/master/Exercicio01

servers: 
 - url: http://localhost:8080
   description: API de teste
paths:
  /api/states:
    post:
      summary: Cria novos estados
      description: "Através desse endpoint você pode criar novos estados brasileiros"
      requestBody: 
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EstadoSemId" 
      responses:
        201:
          description: "Sucesso"
          content:
           application/json:
            schema:
              $ref: "#/components/schemas/Estado"
            
    get: 
      summary: Recupera todos os estados  
      parameters:
        - name: nomeRegiao
          in: query
          description: Limits the number of items on a page
          schema:
            type: string
        - name: sort
          in: query
          description: Limits the number of items on a page
          schema:
            type: string
      responses: 
        200:
          description: Sucesso
          content: 
            application/json:
              schema:
                $ref: "#/components/schemas/Estados"

            
  /api/states/{id}:
    parameters: 
    - name: id
      in: path 
      schema:
        type: integer
      required: true 
    get:
      summary: Recupera uma entidade pelo ID
      responses:
        200:
          description: Sucesso
          content: 
            application/json:
              schema:
                $ref: "#/components/schemas/Estado"
        404:
          description: Estado não encontrado
          content:
            application/json:
              example: "Not Found"
              
    put:
      summary: Altera um estado existente pelo ID
      description: "Através desse endpoint você pode atualizar novos estados brasileiros"
      requestBody: 
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EstadoSemId"
      responses:
        201:
          description: "Sucesso"
          content:
           application/json:
            schema:
              $ref: "#/components/schemas/Estado"
        404:
          description: Estado não encontrado
          content:
            application/json:
              example: "Not Found"

    delete:
      summary: Remove um estado pelo ID
      responses:
        200:
          description: Sucesso

        404:
          description: Estado não encontrado
          content:
            application/json:
              example: "Not Found"
              
components: 
  schemas:
    Estado:
     type: object
     properties:
      id: 
        type: integer
      nome:   
        type: string
      regiao:   
        type: string
      populacao:   
        type: integer
      capital:   
        type: string
      area:   
        type: number
      
    EstadoSemId:
     type: object
     properties:
      nome:   
        type: string
      regiao:   
        type: string
      populacao:   
        type: integer
      capital:   
        type: string
      area:   
        type: number  
        
    Estados: 
      type: array
      items:
        $ref: "#/components/schemas/Estado"

    